version: "3.9"
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - altair-data:/data
    env_file:
      - .env
    networks:
      - altair-network

  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.<branch>.altair.realmit.io`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - altair-network

  wordpress:
    image: wordpress
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.<branch>.altair.realmit.io`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - altair-network

networks:
  altair-network:
    external: true

volumes:
  altair-data:
